### ISSUE TITLE
FieldFormatter choices issues

### ISSUE THREAD

**Issue by davecoates** [prestojs/prestojs#15]
There's a few issues that stop choices from working currently

1. Currently any choices field will break - doesn't pass choices through to the formatter in the default getFormatterForField

2. ChoicesFormatter should use `Array.from` like in the choice widgets so works with any iterable (currently breaks on Map) 

3. ChoicesFormatter only ever returns the value, never the label so actually does nothing

Add test cases please

**Comment by fanglong-alliance** [comment]
https://github.com/prestojs/prestojs/pull/18
