### ISSUE TITLE
Runtime error when building Next.js using SWC

### ISSUE THREAD

**Issue by vbudovski-alliance** [prestojs/prestojs#150]
Next.js version 12 has made SWC the default over Babel. It makes for a much improved developer experience as the build times are significantly reduced. Something about the way that Presto is being built is precluding it from being used in a Next.js application when it is built using SWC. It works fine using the legacy Babel transpiler.

Please see attached code that demonstrates the issue.

To replicate:
- yarn install && yarn dev
- Load http://localhost:3000
- Notice the runtime error: `TypeError: Class constructor UrlPattern cannot be invoked without 'new'`

[swc-error.tar.gz](https://github.com/prestojs/prestojs/files/7491732/swc-error.tar.gz)

**Comment by vbudovski-alliance** [comment]
Including the cjs module does allow it to build. I suspect it might be an issue with either the dependencies (`path-to-regexp` or `query-string` most likely) or the version of babel.

**Comment by davecoates** [comment]
https://github.com/vercel/next.js/issues/30839

can you try next@canary and see if it works?

**Comment by vbudovski-alliance** [comment]
@davecoates Success!
