### ISSUE TITLE
Minor typo in useAsync docs

### ISSUE THREAD

**Issue by ash-plunkett-alliance** [prestojs/prestojs#164]
https://prestojs.com/docs/getting-started/async-functions#useAsync

`// Does API cal lo fetch user`
vs
`// Does API call to fetch user`

<img width="326" alt="Screen Shot 2022-05-17 at 11 21 26 am" src="https://user-images.githubusercontent.com/96507025/168709303-1f2bb7fc-552c-4b60-b2f0-9303ce4c9d62.png">

**Comment by davecoates** [comment]
Thanks - fixed
