### ISSUE TITLE
FilterSet changes

### ISSUE THREAD

**Issue by davecoates** [prestojs/prestojs#47]
Currently FilterSet is using the old `FieldBinder` implementation before I rewrote `ViewModel` as a factory function.

Most of the time a filter set has the same set of fields as a viewmodel but with some modifications (fields added / removed, different labels or help text).

I propose making filtersets a factory as well that you typically generate from a viewmodel

eg.

```
filterSetFactory({
   email: User.fields.email.clone({ helpText: '' }),
   dateJoined: new DateRangeField(),
})
```

I think the general case is that you'd use most fields the same so perhaps some kind of shortcut is in order

```
filterSetFactory(
  User.fields.clone({
    firstName: true,
    lastName: true,
    email: { helpText: '' },
  })
);
```

Implementation wise the differences between a ViewModel and FilterSet is that a FilterSet is never instantiated (it's juts a collection of fields) and has no cache associated with it.

**Comment by levic** [comment]
I assume this is to try to replicate the interface of viewModelFactory as close as possible?

The use cases on the sever side that I find myself using a lot are
- pick subset of fields from a model
- pick fields from a model, but use a field multiple times (eg start / end dates for a timestamp)
- pick a model, but then add a few extra fields that are calculated and don't have a direct correlation with the model

I like the clone shortcut, but it needs some way to merge with others -- does .clone() return a { } than I can then splay with other defs?

eg something like:
```
{
   ...User.fields.clone(...),
   dateJoinedMin: User.fields.dateJoined.clone(),
   dateJoinedMax: User.fields.dateJoined.clone(),
 }
```

**Comment by davecoates** [comment]
yep the `clone` (at the `fields` level) just returns an object defining the fields so can spread like you suggested

**Comment by davecoates** [comment]
Maybe we don't need a fixed concept of a filter set. All we really need (I think) is convenient way to clone sets of fields, eg.

```js
const userFilterFields = {
   ...User.cloneFields({
    firstName: true,
    lastName: true,
    email: { helpText: '' },
  }),
  dateJoined: new DateRangeField(),
};

function UserFilter(props) {
  return (
    <Form {...props>
      <Form.Item field={userFilterFields.firstName} />
      <Form.Item field={userFilterFields.lastName} />
      <Form.Item field={userFilterFields.email} />
      <Form.Item field={userFilterFields.dateJoined} />
    </Form>
  );
}
```

@levic thoughts?

**Comment by davecoates** [comment]
Fang pointed out can just pass the fields direct from the model... perhaps we don't need to bother with any of this? If you need to change something just did it a the `Form.Item` level:

```js
function UserFilter(props) {
  return (
    <Form {...props>
      <Form.Item field={User.fields.firstName} />
      <Form.Item field={User.fields.lastName} />
      <Form.Item field={User.fields.email} help={null} />
      <Form.Item label="Date Joined">
           <Form.Field name="dateJoined" component={DateRangeWidget} />
      </Form.Item>
    </Form>
  );
}
```
