### ISSUE TITLE
Async choices part 2

### ISSUE THREAD

**Issue by davecoates** [prestojs/prestojs#48]
I've been thinking about foreign keys again and my current thoughts are that most of what we want is covered by supporting async choices (ie. choices that are lookup up from an API endpoint or more generally just async choices). I think if interface supported:
1) Define function to list choices (supports pagination & filtering)
2) Define function to resolve label(s) for value(s) [this needs to support multiple values]
3) A function to return a label for an item
4) A function to return the id for an item

I think that's it and covers writing widgets & formatters for foreign keys. Can you think of things we want that aren't supported by this?

So could look like

```jsx
new NumberField({
  asyncChoices: {
    async list({ keywords }) {
         // Can support dynamic imports so don't have to import related models up front
         const User = await import('./User').default;
         const { result } = await User.endpoints.list({ query: { keywords } });
        // TODO: Pagination how?
        return result;
    },
   async retrieve(id) {
       const User = await import('./User').default;
       const { result } = await User.endpoints.get({ urlArgs: { id } });
       // TODO: Multiple records in here or separate function?
       return result;
   },
   getLabels(users) {
      // This is default implementation. Can be customised, eg. to return grouped labels
      return users.map(user => this.getLabel(user));
   },
   getLabel(user) {
       return user.getFullName();
   },
   getId(user) {
     return user._pk;
   },
 }
});
```

some of this can be abstracted to the general case eg. to support standard way of retrieving records from `Endpoint`s

**Comment by levic** [comment]
The only thing I'm unclear about is how grouped labels work.

Are you suggesting that getLabels() returns an opaque data structure that could be anything?

I wonder whether you're not better off from a type/simplicity perspective to always return a list, but there could be extra attributes attached that the widget then uses to construct a hierarchy. (Contra: if reconstructing that array is expensive then is it going to be painful to memoize?)

Edit: to clarify, this would remove the need for getLabels() (but not getLabel()) entirely. (Ultimately would depend on what works out the simplest when widgets + fields are looked at as a whole)

**Comment by davecoates** [comment]
I was thinking that the interface for getLabels would support either flat or grouped which translates to either flat options or options with [optgroup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) given it's a standard thing with HTML select. From a typing perspective this is trivial.

Anything more complicate though would be a custom implementation at the widget AND field level (eg. attaching extra attributes like you suggest). The question is best way to support this. Should we allow any extra attributes to be passed through and just made available on the field?

```
new NumberField({
  asyncChoices: {
      someOtherPropertyMyWidgetCaresAbout: ...
  }
}
```

Currently our static choices don't support this but probably should as it's standard enough I think it should come out of the box

**Comment by davecoates** [comment]
Hmm so it's not so straightforward to implement `list`. If you just call an endpoint like:

```
await Task.endpoints.list.execute()
```

and the response is paginated then it will throw an error (needs the paginator instance passed in)

```
const paginator = new Task.endpoints.list.getPaginatorClass()();
await Task.endpoints.list.execute({ paginator })
```

But even that is insufficient as you have to provide to the paginator the state setter pair (usually with `usePaginator`). But can't really do that from here.

So not really sure what at this stage is the best option to have generic support for async choices that supports the way endpoint works. If the usage was tied to Endpoint it would be easier (the widget is responsible for passing in paginator).

**Comment by davecoates** [comment]
This is current interface working with:

```ts
export type Choice = {
    value: any;
    label: React.ReactNode;
    [x: string]: any;
};
export type ChoicesGrouped = [string, Choice[]];
export type ChoicesResponse = {
    items?: null | (Choice | ChoicesGrouped)[];
    isLoading: boolean;
    [x: string]: any;
};
export type UseChoicesProps = {
    /**
     * When true no choices will be returned. This is useful to prevent lookup
     * up choices before they are need (eg. before a drop down select is opened)
     */
    disabled?: boolean;
    /**
     * Any query string parameters for the request
     */
    query?: Record<string, boolean | string | null | number>;
    /**
     * Whether to accumulate pages as more results are fetched. For example
     * if the first page of results is returned, then the next page is fetched
     * then the combined results for the first two pages will be resolved.
     *
     * This resets whenever `query` changes or if pagination state changes
     * to anything other than the next page.
     */
    accumulatePages?: boolean;
};
type ChoiceValue = string | number;
export interface AsyncChoices<T> {
    useChoices({}: UseChoicesProps): ChoicesResponse;
    // list(params: Record<string, any>): Promise<{ items: T[] } & Record<string, any>>;
    retrieve(value: ChoiceValue | ChoiceValue[]): Promise<T | null>;
    getChoices(items: T[]): (Choice | ChoicesGrouped)[];
    getLabel(item: T): React.ReactNode;
    getValue(item: T): ChoiceValue;
}
```

Main thing of note being that there's now a hook you define on it to handle the list of choices rather than calling a `list` method.

---

After writing the above this morning I think I have a better option now that works more generically but supports pagination. I think pagination belongs in a different module - not @prestojs/rest (it doesn't have any specifically to do with rest or even async behaviour).

Anyway we'd add a hook (name?) `useAsyncList`. To use with an endpoint

```
const paginator = usePaginator(endpoint);
const result = useAsyncList({
    // TODO: rename trigger?
    disabled,
    query,
    // TODO: rename accumulateResults?
    accumulatePages,
    execute: async props => (await endpoint.execute(props)).result,
    paginator,
 });
```

I think this can then work with the original interface whereby the two async functions necessary are `list` and `retrieve`.

So then final usage for getting choices from an endpoint based async choices for a widget:

```tsx
// Definition of async choices
const asyncChoices = {
     async list(props) {
         return (await listEndpoint.execute(props)).result;
     },
    getPaginatorClass() {
        return this.listEndpoint.getPaginatorClass();
    }
    getLabel(item) {
        return item.name;
    },
    getValue(item) {
        return ietm._pk;
    },
    async retrieve(id) {
        return (await retrieveEndpoint.execute({ urlArgs: { id } })).result;
    }
}

// Widget that doesn't need to know the async choices are backed by an Endpoint
function MyWidget({ value }) {
        const [keywords, setKeywords] = useState('')
        const paginator = usePaginator(asyncChoices.getPaginatorClass());
        const { isLoading, error, items } = useAsyncList({
            query: { keywords },
            accumulatePages: true,
            execute: async props => (await listEndpointt.execute(props)).result,
            paginator,
        });
        // when a value is set (eg. when loading an existing record) we may need to look
        // up the value if it's not available in `items`. This does that - return value would be
        // the resolved item, loading status, flag to indicate not found 
        const currentValueResolved = useAsyncValue({
            value,
            existingValues: items,
            execute: async id => (await retrieveEndpoint.execute({ urlArgs: { id } })).result,
        });
        const choices = asyncChoices.getChoices(items);
         
        return (
           <SelectWidgetThingy
               loading={isLoading}
               choices={choices}
               current={currentValueResolved}
           />
       )
}
```

**Comment by levic** [comment]
Some thoughts on this implementation and how it interacts with common use cases:

You've focused on how to write a widget, but creating truly custom widgets is going to be comparatively rare.

In the example above I am making the assumption that you've given an example of the implementation of a custom widget but normally you would just use an existing Widget class, something like `<SelectAsyncWidget asyncChoices={asyncChoices} ... />`,  and asyncChoices itself would normally just be pulled directly from the field definition and passed into the widget?

(Should asyncChoices be a full class or just a typed TS dict?)

**Use Case 1: Custom Labels**
`UserViewModel` where you want to display `(firstName+' '+lastName)` as the label (assuming the __str__ equivalent isn't going to cut it)

You'd override/extend the base asyncChoices and override `getLabel()`?

**Use Case 2: Pagination**

Pagination seems like something that it is ok the widget should be aware of (it will potentially change the UI so it has to be aware of it at some level).

Because of this I think it's acceptable for the widget to be hardcoded to expect a certain type of pagination. You'd then have eg:
- `SelectAsyncWidget`
- `SelectPaginatedAsyncWidget` <- defined in the project as an alias or subclass of `SelectLimitOffsetPaginatedAsyncWidget` 

**Use Case 3: Keywords**
Keyword filter. 

Would be done by passing a filter keyword to `props` in ` async list(props)`?

- `FilterSelectAsyncWidget`
- `FilterSelectLimitOffsetPaginatedAsyncWidget` <- things are getting very cumbersome here; maybe push some of the functionality into the base class an expose as options? Or maybe handle multiple pagination types in a single base pagination class for the simple case?

**Use Case 4: Structured filters**
I'm viewing an organisation and I want to filter the list to only a subset of users.

You would have to create a widget & asyncChoices in this case. they would expose a new prop eg `organizationId` which would be passed to the AsyncChoices.list() method

`<UserSelectAsyncWidget asyncChoices={userAsyncChoices} organizationId={organizationId} 
... >`, where `userAsyncChoices.list({ organizationId: 123})` is how the filter is applied.

**Comment by levic** [comment]
**Use Case 5: Custom Display of Results**

Again, the asyncChoices and the widget would have to be custom.

The `getLabel` function can return something other than just a string; as long as the widget agrees on what it expects to receive and how to render it then we're fine

Example would be a dropdown with columns. `getLabel()` might return `[firstName, lastname]` and the widget would know to render 2-tuples with a multi-column select

**Comment by davecoates** [comment]
Haven't properly read your response but just noting this is out of date, you can see actual implementation here (WIP pull request that depends on https://github.com/prestojs/prestojs/pull/56):

https://github.com/prestojs/prestojs/pull/58/files

It includes example of filtering by keywords, pagination, grouped labels, multiselect
