### ISSUE TITLE
Foreign key support (related view models)

### ISSUE THREAD

**Issue by davecoates** [prestojs/prestojs#49]
For foreign keys they are an extension of #48  - eg. `asyncChoices` is something on the base field that can be provided for Foreign Key fields. The main usage in presto for foreign keys would be for selecting data, eg. cache usage might be

```js
// Get user from cache along with all subscriptions and the product name
cache.get(User, ['firstName', 'lastName', 'email', 'subscriptions.product.name'])
```

But also need it in data fetching. Simplest implementation without trying to replicate graphql is just to bring back the batch API from djrad1 and have the traversal just batch up all the necessary API calls to the backend. I think this would become part of the Endpoint interface via specifying fields to fetch (currently this isn't part of the interface at all).

So maybe the interface for a FK field would be

```
new RelatedManyViewModel({
   to: () => import('./UserSubscription'),
   resolve: (viewModel, ids, fieldNames) => viewModel.endpoints.list(...),
   remoteChoices: {....},
})
```

`asynChoices` handles how values are filtered and shown in a widget so all the `RelatedViewModel` or `RelatedManyViewModel` needs to do is resolve 1 or many objects based on id. Caching implementation can then handle resolving cached objects across multiple caches.

**Comment by levic** [comment]
First thought is that automatic fetches are bad in django -- they're even worse on the frontend, even with batching.

Am concerned that the `resolve` above could be triggered many times.

**Comment by davecoates** [comment]
Yes it could, but it's more a feature than a bug...

**Comment by davecoates** [comment]
I've started on the caching side of this. Here's a test case that shows usage:

```ts
    const Group = viewModelFactory({
        name: new Field<string>(),
    });
    Group.cache.add({ id: 1, name: 'Staff' });

    const User = viewModelFactory({
        name: new Field<string>(),
        groupId: new Field<number>(),
        group: new RelatedViewModelField({
            to: (): Promise<typeof Group> => Promise.resolve(Group),
            sourceFieldName: 'groupId',
        }),
    });
    User.cache.add({ id: 1, name: 'Bob', groupId: 1 });

    const fields = {
        userId: new Field<number>(),
        user: new RelatedViewModelField<typeof User>({
            to: (): Promise<typeof User> => Promise.resolve(User),
            sourceFieldName: 'userId',
        }),
    };
    const Subscription = viewModelFactory(fields);
    Subscription.cache.add({
        id: 1,
        userId: 1,
    });
    const r = Subscription.cache.get(1, ['userId']);
    expect(r?.userId).toBe(1);
    expect(() => r?.user).toThrow(
        /'user' accessed on Subscription but was not instantiated with it/
    );
    expect(() => Subscription.cache.get(1, ['user'])).toThrow(/Call resolveViewModel first/);
    await Subscription.fields.user.resolveViewModel();
    const s = Subscription.cache.get(1, ['user']);
    expect(s?.user.name).toBe('Bob');
    expect(s?.user.group.name).toBe('Staff');
```

The most awkward thing is having to call `resolveViewModel` before this functionality is available. This is necessary because the `to` in the field definition is a promise (eg. allows for dynamic imports on ViewModel). Not sure of a better way to do this without making cache functions async which doesn't seem worth it. It could be possible to have cache's work with suspense if encounters unresolved data but not sure the complexity is worth it. 

This shows simple usage but can select limited nested fields as well using dot notation:

```
Subscription.cache.get(1, ['user.name', 'user.group.name']);
```

Outstanding questions:

1) What should happen if you select `user.group` but `user` or `group` isn't in the cache but we have the id for them? Is it an error? A warning? Silently ignored? I _think_ a warning is probably appropriate.

2) Should `to` always be a promise or accept the viewmodel class up front? I think regardless we should always treat it behind the scenes as async otherwise things may work when no promise => refactor to use dynamic import => code breaks

3) What happens when you access a related field on a record without it having been resolved? Behind the scenes the caching implementation will read from the related cache and set the value on the record by calling `setRelatedViewModel` which makes the value available. ~This sacrifices purity a little bit - a record is no longer strictly immutable. `setRelatedViewModel` can only be called once however - once the value is set it can't be changed. This does mean though that a record could be read from the cache and subsequently have a related value resolved thereby modifying the original record. Should we be concerned? We _could_ handle it in the caching layer but would involve more cloning of records.~ Can't do this actually otherwise equality comparisons will pass which will cause problems with React components not re-rendering when they should. Resolving a foreign key value will have to create a copy with that value set in. Given this I think just passing a nested object when creating a record should be the mechanism by which the value is filled in and populates the related cache:

```js
new User({ group: { name: 'Staff' }, name: 'Dave' });
// Populates `Group` cache as well...
```

This is problematic though given it needs to resolve the FK model (Group) in order to instantiate the ViewModel class and populate the related cache... (see 4 below). ie. value wouldn't be accessible on created record until promise resolved.

4) How to make `resolveViewModel` nicer? One idea is to have `useViewModelCache` do this for you by default for any related field on it... so any dynamic imports will be resolved the first time you call `useViewModelCache` on that ViewModel regardless of whether you need that field (not possible to only do it for fields you ask for _unless_ we do something like have the cache function throw something when not resolved and have `useViewModelCache` handle it). Not supporting async models would be the best... but not sure

**Comment by davecoates** [comment]
Initial implementation is largely done and looks like

```ts
    class Group extends viewModelFactory({
        name: new Field<string>(),
        ownerId: new Field<number>(),
        owner: new RelatedViewModelField({
            // Type here isn't typeof User as it seemed to confuse typescript.. I guess
            // because of the circular reference
            // eslint-disable-next-line @typescript-eslint/no-use-before-define
            to: (): Promise<ViewModelConstructor<any>> => Promise.resolve(User),
            sourceFieldName: 'ownerId',
        }),
    }) {}
    class User extends viewModelFactory({
        name: new Field<string>(),
        groupId: new Field<number>(),
        group: new RelatedViewModelField({
            to: (): Promise<typeof Group> => Promise.resolve(Group),
            sourceFieldName: 'groupId',
        }),
    }) {}
    await User.fields.group.resolveViewModel();
    Group.cache.add({ id: 1, name: 'Staff', ownerId: 1 });
    User.cache.add({ id: 1, name: 'Bob', groupId: 1 });
    expect(
        User.cache.get(1, [
            'name',
            ['group', 'name'],
            ['group', 'owner', 'name'],
            ['group', 'owner', 'group'],
        ])
    ).toBeEqualToRecord(
        new User({
            id: 1,
            name: 'Bob',
            groupId: 1,
            group: {
                id: 1,
                name: 'Staff',
                ownerId: 1,
                owner: {
                    id: 1,
                    name: 'Bob',
                    groupId: 1,
                    group: {
                        id: 1,
                        name: 'Staff',
                        ownerId: 1,
                    },
                },
            },
        })
    );
```

Currently expects `to` to be async which means you have to call `resolveViewModel` before can be used... not sure yet how tedious this would be in practice so open to removing support for async resolve altogether.

I've gone with array syntax rather than dot syntax with the thought that it may be possible to strongly type it down the track:

```
       User.cache.get(1, [
            'name',
            ['group', 'name'],
            ['group', 'owner', 'name'],
            ['group', 'owner', 'group'],
        ])
```

**Comment by levic** [comment]
>            // Type here isn't typeof User as it seemed to confuse typescript.. I guess
>            // because of the circular reference

Django deals with that by fixing up all of the FK references in a second pass once all of the apps have been initialised.

That's not really possible here is it? 
- potential lazy loading of JS modules (could we possibly hook into the webpack module loader?)
- no clear boundary of when "loading" is done (see above though)
- what happens if we have two different implementations of the same model? (eg consider that Admin users and regular Users see a different User model, but they both use the same Group model)

This seems like it might be an issue for down the track; could keep the promise syntax for backwards compat

**Comment by levic** [comment]
Am still not a fan of the inheritance syntax; I wondered what other JS things to and the [most popular ORM](https://sequelize.org/master/) doesn't have a better solution so .. . long live JS?
