### ISSUE TITLE
getWidgetForField relies on unminified class names

### ISSUE THREAD

**Issue by davecoates** [prestojs/prestojs#55]
getWidetForField looks at class names rather than checking types with `instanceof` so can avoid importing all fields if they aren't required => smaller bundle sizes.

This doesn't work with minification however as the class names get mangled.

Options

1) Ditch checking names and just import all the fields

2) Add a required property or function on Field eg, `getClassName() { return 'FileField'; }`

**Comment by levic** [comment]
option 2: mark classes so that they aren't minified (eg uglifyjs has a --keep-fnames option; not sure if that also covers ES6 classes too though).

Seems a bit fragile though, as you'd have to explain how/why to do it for every minifier. OTOH it's a few lines of config code rather than something being on every class.

**Comment by levic** [comment]
option 3: rather than the field specifying its class name, use another abstract identifier, eg "IntegerEdit". Seems a bit cumbersome though as you're introducing this intermediary abstraction layer.

**Comment by davecoates** [comment]
> option 2: mark classes so that they aren't minified (eg uglifyjs has a --keep-fnames option; not sure if that also covers ES6 classes too though).
> 
> Seems a bit fragile though, as you'd have to explain how/why to do it for every minifier. OTOH it's a few lines of config code rather than something being on every class.

I don't think this is a good option as it depends on build step of each project AND uglifying names saves quite a lot overall I think so disabling that just so we can avoid importing fields sounds like a bad trade overall

**Comment by davecoates** [comment]
For now go with option 1
